baseURL = "https://oussoren.github.io"
languageCode = "en-us"
title = "My Hugo Site"
theme = "cactus"

[params]
  description = "My personal website"

# Allow raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress warnings
ignoreLogs = ['warning-goldmark-raw-html']
